/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cs471a1;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public void example(){
        JFrame frame = new JFrame("My First GUI");
        JPanel buttonPane = new JPanel();
        //frame.setLayout(new BoxLayout(buttonPane, BoxLayout.LINE_AXIS));
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(1600,700);
        JButton button = new JButton("Press");//Sets up button
        button.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                test_code();
            }});
        JButton newButton = new JButton("test");
        newButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e){
                frame.revalidate();
            }
        });
        
        JButton button1 = new JButton("Button 1");
        JButton button2 = new JButton("Button 2");
        buttonPane.add(BorderLayout.NORTH, button1);
        buttonPane.add(BorderLayout.SOUTH, button2);
        //frame.add(button); // Adds Button to content pane ofbuttonPane
        buttonPane.add(button);
        buttonPane.add(Box.createHorizontalStrut(5));
        buttonPane.add(new JSeparator(SwingConstants.VERTICAL));
        buttonPane.add(Box.createHorizontalStrut(5));
        buttonPane.add(button1);
        buttonPane.add(button2);
        buttonPane.setBorder(BorderFactory.createEmptyBorder(5,5,5,5));
        frame.add(BorderLayout.NORTH, newButton);
        frame.add(BorderLayout.SOUTH, buttonPane);
        frame.setVisible(true);//Makes window visable
    }
    
    public void test_code(){
        //Creating the Frame
        JFrame frame = new JFrame("Chat Frame");
        frame.setSize(400, 400);

        //Creating the MenuBar and adding components
        JMenuBar mb = new JMenuBar();
        JMenu m1 = new JMenu("FILE");
        JMenu m2 = new JMenu("Help");
        mb.add(m1);
        mb.add(m2);
        JMenuItem m11 = new JMenuItem("Open");
        JMenuItem m22 = new JMenuItem("Save as");
        m1.add(m11);
        m1.add(m22);

        //Creating the panel at bottom and adding components
        JPanel panel = new JPanel(); // the panel is not visible in output
        JLabel label = new JLabel("Enter Text");
        JTextField tf = new JTextField(10); // accepts upto 10 characters
        JButton send = new JButton("Send");
        JButton reset = new JButton("Reset");
        panel.add(label); // Components Added using Flow Layout
        panel.add(tf);
        panel.add(send);
        panel.add(reset);

        // Text Area at the Center
        JTextArea ta = new JTextArea();

        //Adding Components to the frame.
        frame.getContentPane().add(BorderLayout.SOUTH, panel);//Tells frame where to put what
        frame.getContentPane().add(BorderLayout.NORTH, mb);
        frame.getContentPane().add(BorderLayout.CENTER, ta);
        frame.setVisible(true);
    }

    public void OSGUI(){
        JFrame window = new JFrame("OSGUI");
        window.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        window.setSize(1600,700);
        JPanel PQ = new JPanel();
        JPanel CurrentProcess = new JPanel();
        JPanel NewProcess = new JPanel();
        JPanel BlockedList = new JPanel();

        window.add(BorderLayout.NORTH, CurrentProcess);
        window.add(BorderLayout.SOUTH, NewProcess);
        window.add(BorderLayout.WEST, BlockedList);
        window.add(BorderLayout.CENTER, PQ);
    }

    public static void main(String[] args) {
        App Prog = new App();
        Prog.OSGUI();
    }

}
